apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hjq8hgvhb-nodejs 
  janus-idp.io/tekton: hjq8hgvhb-nodejs
  backstage.io/kubernetes-id: hjq8hgvhb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hjq8hgvhb-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml